FROM node:22-bookworm-slim AS base

# Install build tools so node-gyp and native packages work cleanly
RUN apt-get update && apt-get install -y python3 make g++ gcc && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@10.28.0 --activate

WORKDIR /app

# Copy all repository files
COPY . .

# Install all workspace dependencies
RUN pnpm install --frozen-lockfile

# Build the API server target directly using workspace filters
RUN pnpm --filter @workspace/api-server... run build

# Fail the build inside Docker immediately if dist/index.js was not emitted
RUN test -f artifacts/api-server/dist/index.js || (echo "FATAL: artifacts/api-server/dist/index.js was not generated by build step!" && exit 1)

EXPOSE 3000

CMD ["node", "artifacts/api-server/dist/index.js"]
