[providers]
providers = ['node']

[phases.setup]
nixPkgs = ['pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile --ignore-scripts']

[phases.build]
cmds = ['pnpm --filter ./artifacts/opportunity-tracker run build']

[start]
cmd = 'pnpm --filter ./artifacts/opportunity-tracker run preview --host 0.0.0.0 --port $PORT'
