// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ritual/EmberRitual.tsx": () => import("../components/mockups/ritual/EmberRitual.tsx"),
  "./components/mockups/opportunity/SignalDesk.tsx": () => import("../components/mockups/opportunity/SignalDesk.tsx")
};
